#!/usr/bin/env python3
"""Seed the BioPipelines backbone redesign pipeline.

Implements Application 2 from:
  Quargnali & Rivera-Fuentes, "BioPipelines: Accessible Computational Protein
  and Ligand Design for Chemical Biologists", bioRxiv 2026.
  DOI: https://doi.org/10.64898/2026.03.11.711024

Pipeline topology (Figure 2):
  RFdiffusion → ProteinMPNN → ESMFold

  Paper quote (Application 2):
    "RFdiffusion is called to generate ten new protein backbones …
     After this step, the workflow continues … with inverse folding of the
     new backbones by ProteinMPNN, which generates two sequences for each
     backbone generated by RFdiffusion, and structure validation by AlphaFold2."

  Note: This platform uses ESMFold in place of AlphaFold2 for folding designed
  FASTA sequences directly (the platform's alphafold_monomer fetches EBI by
  UniProt accession and cannot fold arbitrary sequences).

Run:
    python scripts/seed_biopipelines_backbone_design.py
"""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

DB_PATH = Path(__file__).resolve().parents[1] / "backend" / "protein_design.db"

PIPELINE = {
    "id": "pipe-biopipelines-backbone-design",
    "name": "BioPipelines · Backbone Redesign (RFdiffusion → ProteinMPNN → ESMFold)",
    "schema_version": "1",
    "nodes": [
        # ── Node 1: RFdiffusion de novo backbone generation ──────────────────
        # Paper Figure 2: "RFdiffusion is called to generate ten new protein
        # backbones, replacing the segment A118-160 (LID) with a new backbone
        # of lengths between 50 and 70 amino acids."
        {
            "id": "rfdiffusion",
            "tool": "rfdiffusion",
            "params": {
                "num_designs": 1,
                "num_residues": 60,   # midpoint of paper's 50–70 aa range
                "diffusion_steps": 50,
                "target_pdb": "",
                "hotspot_residues": "",
            },
            "position": {"x": 100, "y": 300},
        },
        # ── Node 2: ProteinMPNN inverse folding ───────────────────────────────
        # Paper Figure 2: "inverse folding of the new backbones by ProteinMPNN,
        # which generates two sequences for each backbone generated by
        # RFdiffusion"
        {
            "id": "proteinmpnn",
            "tool": "proteinmpnn",
            "params": {
                "num_sequences": 2,
                "sampling_temp": 0.1,
            },
            "position": {"x": 450, "y": 300},
        },
        # ── Node 3: ESMFold structure validation ──────────────────────────────
        # Paper Figure 2: "structure validation by AlphaFold2"
        # ESMFold substituted because it accepts FASTA sequences directly
        # (alphafold_monomer requires a UniProt accession, not a designed seq).
        {
            "id": "esmfold",
            "tool": "esmfold",
            "params": {},
            "position": {"x": 800, "y": 300},
        },
    ],
    "edges": [
        # Paper Figure 2: RFdiffusion backbone → ProteinMPNN structure input
        {"source": "rfdiffusion.backbone", "target": "proteinmpnn.structure"},
        # Paper Figure 2: ProteinMPNN sequence → structure validation
        {"source": "proteinmpnn.sequence", "target": "esmfold.sequence"},
    ],
}


def main() -> None:
    if not DB_PATH.exists():
        raise SystemExit(f"DB not found at {DB_PATH} — is the backend initialised?")

    conn = sqlite3.connect(DB_PATH)
    now = datetime.now(timezone.utc).isoformat()

    conn.execute(
        "INSERT OR REPLACE INTO pipelines (id, name, data, created_at, updated_at)"
        " VALUES (?,?,?,?,?)",
        (PIPELINE["id"], PIPELINE["name"], json.dumps(PIPELINE), now, now),
    )
    conn.commit()
    conn.close()

    print(f"Created pipeline: {PIPELINE['id']}")
    print(f"Name: {PIPELINE['name']}")
    print("Open the frontend → Pipelines list → load this pipeline on the canvas.")
    print()
    print("Pipeline topology:")
    print("  RFdiffusion (backbone) → ProteinMPNN (sequence) → ESMFold (structure)")
    print()
    print("Reference: Quargnali & Rivera-Fuentes, BioPipelines, bioRxiv 2026")
    print("  https://doi.org/10.64898/2026.03.11.711024  Figure 2 / Application 2")


if __name__ == "__main__":
    main()
